"use client";

import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { BundleApplicationStatus, CartBundleApplication, CartItem } from "@/src/lib/types/cart";
import { addBusinessBreadcrumb } from "@/src/lib/observability";
import type { BundleSelectionAllocation } from "@/src/lib/utils/bundleVoucher";

export function computeFinalClientPrice(item: CartItem): number {
  if (item.category === "extras") {
    return item.itemVoucherId ? 0 : item.unitPrice;
  }
  const baseDrinkPrice = item.unitPrice - item.addonsPrice;
  const voucherCredit = item.productVoucherDiscountVnd ?? 0;
  
  // PRODUCT credit caps at drink price — never spills into addon
  const drinkAfterCredit = Math.max(0, baseDrinkPrice - voucherCredit);
  
  // ADDON voucher discounts apply independently
  const addonDiscount = item.addonVouchers?.reduce((sum, v) => sum + v.discountVnd, 0) ?? 0;
  const finalAddonsPrice = Math.max(0, item.addonsPrice - addonDiscount);
  
  return drinkAfterCredit + finalAddonsPrice;
}

/** Release one voucher token from every cart line except its new target line. */
export function releaseVoucherFromOtherCartLines(
  items: CartItem[],
  voucherId: string,
  targetCartId: string | null,
): CartItem[] {
  return items.map((item) => {
    if (
      item.cartId === targetCartId ||
      (item.productVoucherId !== voucherId && item.itemVoucherId !== voucherId)
    ) {
      return item;
    }
    const released = {
      ...item,
      productVoucherId: undefined,
      productVoucherDiscountVnd: undefined,
      productVoucherType: undefined,
      itemVoucherId: undefined,
    };
    return { ...released, clientPriceVnd: computeFinalClientPrice(released) };
  });
}

function normalizeUniqueCartVouchers(items: CartItem[]): CartItem[] {
  const ownerByVoucher = new Map<string, string>();
  for (const item of items) {
    const voucherId = item.itemVoucherId ?? item.productVoucherId;
    if (voucherId) ownerByVoucher.set(voucherId, item.cartId);
  }
  return items.map((item) => {
    const voucherId = item.itemVoucherId ?? item.productVoucherId;
    if (!voucherId || ownerByVoucher.get(voucherId) === item.cartId) return item;
    const released = {
      ...item,
      productVoucherId: undefined,
      productVoucherDiscountVnd: undefined,
      productVoucherType: undefined,
      itemVoucherId: undefined,
    };
    return { ...released, clientPriceVnd: computeFinalClientPrice(released) };
  });
}

/** Remove only cart effects that were explicitly generated by one BUNDLE application. */
export function removeBundleEffects(items: CartItem[], application: CartBundleApplication): CartItem[] {
  const lineIds = new Set(application.created_reward_effects.flatMap((effect) => effect.kind === "LINE" ? [effect.client_line_id] : []));
  return items.filter((item) => !lineIds.has(item.cartId)).map((item) => {
    const addonEffects = application.created_reward_effects.filter(
      (effect): effect is Extract<CartBundleApplication["created_reward_effects"][number], { kind: "ADDON" }> =>
        effect.kind === "ADDON" && effect.client_line_id === item.cartId,
    );
    if (addonEffects.length === 0) return item;
    const effectByOption = new Map<string, number>();
    for (const effect of addonEffects) effectByOption.set(effect.addon_option_id, (effectByOption.get(effect.addon_option_id) ?? 0) + effect.quantity);
    const quantityAddonOptions = item.quantityAddonOptions.flatMap((addon) => {
      const quantity = addon.quantity - (effectByOption.get(addon.option_id) ?? 0);
      return quantity > 0 ? [{ ...addon, quantity }] : [];
    });
    const selectedOptionIds = item.selectedOptionIds.filter((id) => (effectByOption.get(id) ?? 0) < 1);
    const removedPrice = [...effectByOption.entries()].reduce((sum, [id, quantity]) => sum + (item.addonPrices[id] ?? 0) * quantity, 0);
    const next = { ...item, quantityAddonOptions, selectedOptionIds, addonsPrice: Math.max(0, item.addonsPrice - removedPrice) };
    return { ...next, clientPriceVnd: computeFinalClientPrice(next) };
  });
}

/** Remove generated rewards only for targeted BUNDLE applications and restore verified siblings. */
export function markBundleApplicationsUnavailableState(
  items: CartItem[],
  applications: CartBundleApplication[],
  message: string,
  voucherTokens: string[],
): { items: CartItem[]; bundleApplications: CartBundleApplication[] } {
  const unavailableTokens = new Set(voucherTokens);
  const unavailableApplications = applications.filter((application) =>
    unavailableTokens.has(application.voucher_qr_token),
  );
  return {
    items: unavailableApplications.reduce(
      (currentItems, application) => removeBundleEffects(currentItems, application),
      items,
    ),
    bundleApplications: applications.map((application) => {
      if (unavailableTokens.has(application.voucher_qr_token)) {
        return {
          ...application,
          created_reward_effects: [],
          status: "UNAVAILABLE" as const,
          message,
        };
      }
      return application.status === "VERIFY_FAILED"
        ? { ...application, status: "READY" as const, message: undefined }
        : application;
    }),
  };
}

/** Retain only auto-created effects still represented by the application's selected reward allocations. */
export function retainBundleRewardEffects(
  previous: CartBundleApplication["created_reward_effects"],
  rewardAllocations: BundleSelectionAllocation[],
  addedEffect?: CartBundleApplication["created_reward_effects"][number],
): CartBundleApplication["created_reward_effects"] {
  const candidates = addedEffect ? [...previous, addedEffect] : previous;
  const retained = candidates.filter((effect) => rewardAllocations.some((allocation) =>
    allocation.client_line_id === effect.client_line_id &&
    (effect.kind === "LINE" ? allocation.addon_option_id === undefined : allocation.addon_option_id === effect.addon_option_id),
  ));
  const seen = new Set<string>();
  return retained.filter((effect) => {
    const key = effect.kind === "LINE"
      ? `LINE:${effect.client_line_id}`
      : `ADDON:${effect.client_line_id}:${effect.addon_option_id}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

interface CartState {
  items: CartItem[];
  isCartOpen: boolean;

  setCartOpen: (open: boolean) => void;
  addItem: (newItem: Omit<CartItem, "cartId">) => string;
  removeItem: (cartId: string) => void;
  updateItem: (cartId: string, updates: Partial<CartItem>) => void;
  updateQuantity: (cartId: string, quantity: number) => void;
  clearCart: () => void;
  /**
   * Applies a PRODUCT voucher credit to a cart item.
   * Reduces clientPriceVnd by up to coveredPriceVnd (floor at 0).
   * Stores the original price so it can be restored on voucher removal.
   */
  applyProductVoucher: (cartId: string, voucherId: string, coveredPriceVnd: number, voucherType?: "PRODUCT" | "PRODUCT_DISCOUNT") => void;
  /**
   * Removes a PRODUCT voucher from a cart item and restores the original price.
   */
  removeProductVoucher: (cartId: string) => void;
  applyAddonVoucher: (cartId: string, voucherId: string, addonOptionId: string) => void;
  removeAddonVoucher: (cartId: string, voucherId: string) => void;
  removeVoucherEffects: (voucherToken: string) => void;
  selectedVoucherIds: string[];
  setSelectedVoucherIds: (ids: string[] | ((prev: string[]) => string[])) => void;
  bundleApplications: CartBundleApplication[];
  commitBundleApplication: (application: CartBundleApplication) => void;
  removeBundleApplication: (voucherToken: string) => void;
  clearBundleApplications: () => void;
  reconcileBundleApplications: (ownerKey: string | null) => void;
  setBundleApplicationStatus: (voucherToken: string, status: BundleApplicationStatus, message?: string) => void;
  markBundleApplicationsVerifyFailed: (message: string) => void;
  markBundleApplicationsUnavailable: (message: string, voucherTokens: string[]) => void;
}

type PersistedCartState = Partial<Pick<CartState, "items" | "isCartOpen" | "selectedVoucherIds" | "bundleApplications">>;

/** Migrate persisted cart data while retaining items and removing legacy voucher identifiers. */
export function migrateCartState(
  persistedState: unknown,
  fromVersion: number,
): PersistedCartState {
  const old = persistedState as PersistedCartState;
  if (!old.items) return old;

  const sizeMap: Record<string, import("@/src/lib/types/menu").Size> = {
    M: "SMALL",
    L: "MEDIUM",
    XL: "LARGE",
  };

  old.items = old.items.map((item) => {
    const sizedItem = fromVersion < 2
      ? { ...item, size: item.size ? (sizeMap[item.size] ?? "SMALL") : null }
      : item;
    const voucherSafeItem = fromVersion < 3 ? {
      ...sizedItem,
      clientPriceVnd: sizedItem.originalClientPriceVnd ?? sizedItem.unitPrice,
      productVoucherId: undefined,
      productVoucherDiscountVnd: undefined,
      productVoucherType: undefined,
      addonVouchers: [],
    } : sizedItem;
    const baseLiquidSafeItem = fromVersion < 5 && voucherSafeItem.selectedMilkTypeId
      ? { ...voucherSafeItem, selectedBaseLiquidId: voucherSafeItem.selectedMilkTypeId }
      : voucherSafeItem;
    const itemVoucherSafeItem = fromVersion < 6 && baseLiquidSafeItem.itemVoucherId
      ? {
          ...baseLiquidSafeItem,
          itemVoucherId: undefined,
          clientPriceVnd: baseLiquidSafeItem.originalClientPriceVnd ?? baseLiquidSafeItem.unitPrice,
        }
      : baseLiquidSafeItem;
    if (fromVersion >= 4) return itemVoucherSafeItem;

    if (itemVoucherSafeItem.size === null) return itemVoucherSafeItem;
    const retainedOptionIds = itemVoucherSafeItem.selectedOptionIds.filter(
      (optionId) => (itemVoucherSafeItem.addonPrices[optionId] ?? 0) > 0,
    );
    const retainedOptionIdSet = new Set([
      ...retainedOptionIds,
      ...itemVoucherSafeItem.quantityAddonOptions.map((option) => option.option_id),
    ]);
    const retainedPrices = Object.fromEntries(
      Object.entries(itemVoucherSafeItem.addonPrices).filter(
        ([optionId, price]) => price > 0 || retainedOptionIdSet.has(optionId),
      ),
    );
    return {
      ...itemVoucherSafeItem,
      selectedOptionIds: retainedOptionIds,
      addonPrices: retainedPrices,
      addonVouchers: itemVoucherSafeItem.addonVouchers?.filter(
        (voucher) => retainedOptionIdSet.has(voucher.addonOptionId),
      ),
    };
  });

  old.items = normalizeUniqueCartVouchers(old.items);

  if (fromVersion < 3) old.selectedVoucherIds = [];
  if (fromVersion < 8) {
    old.items = old.items.map((item) => ({
      ...item,
      bundleQualifierVoucherToken: undefined,
      bundleRewardVoucherToken: undefined,
    }));
    old.bundleApplications = [];
  }
  return old;
}

/**
 * useCartStore — global shopping cart state managed by Zustand.
 * Persisted to localStorage so the fish stay in the bag after refresh.
 */
export const useCartStore = create<CartState>()(
  persist(
    (set, get) => ({
      items: [],
      isCartOpen: false,
      selectedVoucherIds: [],
      bundleApplications: [],
      setCartOpen: (open) => set({ isCartOpen: open }),
      setSelectedVoucherIds: (ids) => set({ 
        selectedVoucherIds: typeof ids === "function" ? ids(get().selectedVoucherIds) : ids 
      }),
      commitBundleApplication: (application) => set((state) => {
        const previous = state.bundleApplications.find((item) => item.voucher_qr_token === application.voucher_qr_token);
        const retainedEffects = new Set(application.created_reward_effects.map((effect) => effect.kind === "LINE" ? `LINE:${effect.client_line_id}` : `ADDON:${effect.client_line_id}:${effect.addon_option_id}`));
        const stalePrevious = previous ? {
          ...previous,
          created_reward_effects: previous.created_reward_effects.filter((effect) => !retainedEffects.has(effect.kind === "LINE" ? `LINE:${effect.client_line_id}` : `ADDON:${effect.client_line_id}:${effect.addon_option_id}`)),
        } : null;
        return {
          items: stalePrevious ? removeBundleEffects(state.items, stalePrevious) : state.items,
          bundleApplications: [...state.bundleApplications.filter((item) => item.voucher_qr_token !== application.voucher_qr_token), { ...application, status: application.status ?? "REVALIDATING" }],
        };
      }),
      removeBundleApplication: (voucherToken) => set((state) => {
        const application = state.bundleApplications.find((item) => item.voucher_qr_token === voucherToken);
        return application ? {
          items: removeBundleEffects(state.items, application),
          bundleApplications: state.bundleApplications.filter((item) => item.voucher_qr_token !== voucherToken),
        } : {};
      }),
      clearBundleApplications: () => set((state) => ({
        items: state.bundleApplications.reduce((items, application) => removeBundleEffects(items, application), state.items),
        bundleApplications: [],
      })),
      reconcileBundleApplications: (ownerKey) => set((state) => {
        const invalid = state.bundleApplications.filter((application) => !ownerKey || application.owner_key !== ownerKey);
        const retained = state.bundleApplications.filter((application) => !invalid.includes(application)).map((application) => {
          if (application.status === "UNAVAILABLE" || application.status === "VERIFY_FAILED") return application;
          const lineIds = new Set(state.items.map((item) => item.cartId));
          const hasMissingLine = [...application.qualifier_allocations, ...application.reward_allocations].some((allocation) => !lineIds.has(allocation.client_line_id));
          return hasMissingLine ? { ...application, status: "CONFLICT" as const, message: "Giỏ đã thay đổi, vui lòng chọn lại ưu đãi" } : { ...application, status: "REVALIDATING" as const };
        });
        return { items: invalid.reduce((items, application) => removeBundleEffects(items, application), state.items), bundleApplications: retained };
      }),
      setBundleApplicationStatus: (voucherToken, status, message) => set((state) => ({
        bundleApplications: state.bundleApplications.map((application) => application.voucher_qr_token === voucherToken ? { ...application, status, message } : application),
      })),
      markBundleApplicationsVerifyFailed: (message) => set((state) => ({
        bundleApplications: state.bundleApplications.map((application) => ({
          ...application,
          status: "VERIFY_FAILED" as const,
          message,
        })),
      })),
      markBundleApplicationsUnavailable: (message, voucherTokens) => set((state) =>
        markBundleApplicationsUnavailableState(
          state.items,
          state.bundleApplications,
          message,
          voucherTokens,
        ),
      ),

      addItem: (newItem) => {
        const cartId = crypto.randomUUID();
        const fullItem: CartItem = { ...newItem, cartId };
        set((state) => ({
          items: [
            ...(newItem.itemVoucherId
              ? releaseVoucherFromOtherCartLines(state.items, newItem.itemVoucherId, null)
              : state.items),
            fullItem,
          ],
        }));
        addBusinessBreadcrumb("cart.add", {
          category: newItem.category,
          quantity: newItem.quantity,
        });
        return cartId;
      },

      removeItem: (cartId) => {
        set({
          items: get().items.filter((i) => i.cartId !== cartId),
        });
        addBusinessBreadcrumb("cart.remove", {
          remaining_items: get().items.length,
        });
      },

      updateItem: (cartId, updates) => {
        set({
          items: (updates.itemVoucherId
            ? releaseVoucherFromOtherCartLines(get().items, updates.itemVoucherId, cartId)
            : get().items).map((i) => {
            if (i.cartId !== cartId) return i;
            return { ...i, ...updates };
          }),
        });
      },

      updateQuantity: (cartId, quantity) => {
        set({
          items: get().items.map((i) => {
            if (i.cartId !== cartId) return i;
            // Prevent increasing quantity for items with vouchers
            if ((i.productVoucherId || i.itemVoucherId || (i.addonVouchers && i.addonVouchers.length > 0)) && quantity > 1) {
              return i;
            }
            return { ...i, quantity: Math.max(1, quantity) };
          }),
        });
      },

      clearCart: () => set({ items: [], selectedVoucherIds: [], bundleApplications: [] }),

      applyProductVoucher: (cartId, voucherId, coveredPriceVnd, voucherType = "PRODUCT") => {
        const currentItems = get().items.map((i) => {
          if (i.productVoucherId === voucherId || i.itemVoucherId === voucherId) {
            const nextI = { ...i, productVoucherId: undefined, productVoucherDiscountVnd: undefined, productVoucherType: undefined, itemVoucherId: undefined };
            nextI.clientPriceVnd = computeFinalClientPrice(nextI);
            return nextI;
          }
          return i;
        });

        const itemIndex = currentItems.findIndex((i) => i.cartId === cartId);
        if (itemIndex === -1) return;

        const item = currentItems[itemIndex];
        const isItemVoucher = item.category === "extras";
        const nextItem = {
          ...item,
          productVoucherId: isItemVoucher ? undefined : voucherId,
          productVoucherDiscountVnd: isItemVoucher ? undefined : coveredPriceVnd,
          productVoucherType: isItemVoucher ? undefined : voucherType,
          itemVoucherId: isItemVoucher ? voucherId : undefined,
        };
        const discounted = computeFinalClientPrice(nextItem);
        nextItem.clientPriceVnd = discounted;

        if (item.quantity === 1) {
          currentItems[itemIndex] = nextItem;
          set({ items: currentItems });
          addBusinessBreadcrumb("voucher.apply", { voucher_type: isItemVoucher ? "ITEM" : "PRODUCT" });
          return;
        }

        // Split the item if quantity > 1
        const newItem = {
          ...nextItem,
          cartId: crypto.randomUUID(),
          quantity: 1,
        };

        currentItems[itemIndex] = { ...item, quantity: item.quantity - 1 };
        currentItems.splice(itemIndex + 1, 0, newItem);

        set({ items: currentItems });
        addBusinessBreadcrumb("voucher.apply", { voucher_type: isItemVoucher ? "ITEM" : "PRODUCT" });
      },

      removeProductVoucher: (cartId) => {
        set({
          items: get().items.map((i) => {
            if (i.cartId !== cartId) return i;
            const nextItem = { ...i, productVoucherId: undefined, productVoucherDiscountVnd: undefined, productVoucherType: undefined, itemVoucherId: undefined };
            nextItem.clientPriceVnd = computeFinalClientPrice(nextItem);
            return nextItem;
          }),
        });
        addBusinessBreadcrumb("voucher.remove", { voucher_type: "PRODUCT" });
      },

      applyAddonVoucher: (cartId, voucherId, addonOptionId) => {
        const currentItems = get().items.map((i) => {
          if (i.addonVouchers?.some(v => v.voucherId === voucherId)) {
            const nextI = { ...i, addonVouchers: i.addonVouchers.filter(v => v.voucherId !== voucherId) };
            nextI.clientPriceVnd = computeFinalClientPrice(nextI);
            return nextI;
          }
          return i;
        });

        const itemIndex = currentItems.findIndex((i) => i.cartId === cartId);
        if (itemIndex === -1) return;

        const item = currentItems[itemIndex];
        
        const newAddonVouchers = item.addonVouchers ? [...item.addonVouchers] : [];
        const existingIdx = newAddonVouchers.findIndex(v => v.addonOptionId === addonOptionId);
        
        const toppingPrice = item.addonPrices?.[addonOptionId] ?? 0;
        const newVoucher = { voucherId, addonOptionId, discountVnd: toppingPrice };

        if (existingIdx !== -1) {
          newAddonVouchers[existingIdx] = newVoucher;
        } else {
          newAddonVouchers.push(newVoucher);
        }

        const nextItem = { ...item, addonVouchers: newAddonVouchers };
        const discounted = computeFinalClientPrice(nextItem);
        nextItem.clientPriceVnd = discounted;

        if (item.quantity === 1) {
          currentItems[itemIndex] = nextItem;
          set({ items: currentItems });
          return;
        }

        // Split the item if quantity > 1
        const newItem = {
          ...nextItem,
          cartId: crypto.randomUUID(),
          quantity: 1,
        };

        currentItems[itemIndex] = { ...item, quantity: item.quantity - 1 };
        currentItems.splice(itemIndex + 1, 0, newItem);

        set({ items: currentItems });
      },

      removeAddonVoucher: (cartId, voucherId) => {
        set({
          items: get().items.map((i) => {
            if (i.cartId !== cartId) return i;
            if (!i.addonVouchers) return i;
            const nextItem = { ...i, addonVouchers: i.addonVouchers.filter(v => v.voucherId !== voucherId) };
            nextItem.clientPriceVnd = computeFinalClientPrice(nextItem);
            return nextItem;
          }),
        });
      },
      removeVoucherEffects: (voucherToken) => set((state) => {
        const bundleApplication = state.bundleApplications.find(
          (application) => application.voucher_qr_token === voucherToken,
        );
        const bundleSafeItems = bundleApplication
          ? removeBundleEffects(state.items, bundleApplication)
          : state.items;
        const items = bundleSafeItems.map((item) => {
          const hasItemEffect =
            item.productVoucherId === voucherToken || item.itemVoucherId === voucherToken;
          const hasAddonEffect = item.addonVouchers?.some(
            (voucher) => voucher.voucherId === voucherToken,
          ) ?? false;
          if (!hasItemEffect && !hasAddonEffect) return item;
          const nextItem = {
            ...item,
            ...(hasItemEffect
              ? {
                  productVoucherId: undefined,
                  productVoucherDiscountVnd: undefined,
                  productVoucherType: undefined,
                  itemVoucherId: undefined,
                }
              : {}),
            ...(hasAddonEffect
              ? {
                  addonVouchers: item.addonVouchers?.filter(
                    (voucher) => voucher.voucherId !== voucherToken,
                  ),
                }
              : {}),
          };
          return { ...nextItem, clientPriceVnd: computeFinalClientPrice(nextItem) };
        });
        return {
          items,
          selectedVoucherIds: state.selectedVoucherIds.filter(
            (token) => token !== voucherToken,
          ),
          bundleApplications: state.bundleApplications.filter(
            (application) => application.voucher_qr_token !== voucherToken,
          ),
        };
      }),
    }),
    {
      name: "bcbm-cart",
      version: 8,
      /**
       * Auto-migrate old localStorage cart data:
       * Size M → SMALL, L → MEDIUM, XL → LARGE (Big-Bang strategy).
       * Runs once when version upgrades from <2 to 2.
       */
      migrate: migrateCartState,
      partialize: (state) => ({
        items: state.items,
        isCartOpen: state.isCartOpen,
        selectedVoucherIds: state.selectedVoucherIds,
        bundleApplications: state.bundleApplications,
      }),
    }
  )
);

/** Computed helpers for easier usage in components */
export const useCartTotalItems = () =>
  useCartStore((s) => s.items.reduce((sum, i) => sum + i.quantity, 0));

export const useCartTotalPrice = () =>
  useCartStore((s) => s.items.reduce((sum, i) => sum + i.clientPriceVnd * i.quantity, 0));
