import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

const mockSearchOwners = vi.fn();
vi.mock("@/src/services/adminVoucherService", async () => {
  const actual = await vi.importActual<typeof import("@/src/services/adminVoucherService")>("@/src/services/adminVoucherService");
  return { ...actual, searchVoucherPackageOwners: (...args: unknown[]) => mockSearchOwners(...args) };
});
vi.mock("@/src/components/ui/ResponsiveOverlay", () => ({ ResponsiveOverlay: ({ open, children, footer, onOpenChange }: { open: boolean; children: React.ReactNode; footer?: React.ReactNode; onOpenChange: (open: boolean) => void }) => open ? <div><button onClick={() => onOpenChange(false)}>Đóng overlay</button>{children}{footer}</div> : null }));
vi.mock("@/src/components/ui/ConfirmModal", () => ({ ConfirmModal: ({ isOpen, title, onConfirm }: { isOpen: boolean; title: string; onConfirm: () => void }) => isOpen ? <div><span>{title}</span><button onClick={onConfirm}>Xác nhận modal</button></div> : null }));
vi.mock("framer-motion", () => ({ motion: { button: (props: React.ButtonHTMLAttributes<HTMLButtonElement> & { whileTap?: unknown }) => { const { whileTap, ...buttonProps } = props; void whileTap; return <button {...buttonProps} />; } } }));

import { AdminVoucherPackageCard } from "@/src/components/admin/AdminVoucherPackageCard";
import { AdminVoucherPackageDetail } from "@/src/components/admin/AdminVoucherPackageDetail";
import type { VoucherPackage } from "@/src/services/adminVoucherService";

const pkg: VoucherPackage = { id: "pkg", name: "Giảm Matcha", description: "Mô tả", voucher_type: "PRODUCT_DISCOUNT", acquisition_mode: "FREE_CLAIM", points_cost: 0, ends_at: "2026-08-27T17:00:00.000Z", discount_type: "FIXED", discount_value: 20_000, product_discount_mode: "FIXED_AMOUNT", menu_item_id: "menu", eligible_menu_items: [{ menu_item_id: "menu", name: "Matcha Latte", category: "latte", is_available: true, is_seasonal: false }], eligible_sizes: ["SMALL", "MEDIUM"], reference_size: null, size: null, matcha_powder_id: null, milk_type_id: null, included_addon_option_ids: [], addon_option_id: null, covered_price_vnd: null, covered_delivery_fee_vnd: null, min_order_vnd: 50_000, is_active: true, expires_after_days: 7, quantity: null, max_per_user: 1, created_at: "2026-08-01T00:00:00Z", menuItem: { name: "Matcha Latte", is_available: true }, addonOption: null, bundleRule: null, stats: { issued_count: 4, active_count: 1, reserved_count: 1, redeemed_count: 2, expired_count: 0, refunded_count: 0, remaining_quantity: null } };

describe("Quản lý package voucher — component", () => {
  beforeEach(() => { vi.clearAllMocks(); mockSearchOwners.mockResolvedValue({ users: [], next_cursor: null }); });
  it("card hiển thị điều kiện chính và hạn phát hành bao gồm ngày cuối", () => { render(<AdminVoucherPackageCard pkg={pkg} onOpen={vi.fn()} />); expect(screen.getByText(/Đơn từ 50.000đ/)).toBeTruthy(); expect(screen.getByText(/27\/8\/2026/)).toBeTruthy(); expect(screen.getByText(/Đã dùng 2\/4/)).toBeTruthy(); });
  it("detail hiển thị cấu hình loại và mọi thống kê", () => { render(<AdminVoucherPackageDetail pkg={pkg} open saving={false} onClose={vi.fn()} onSave={vi.fn()} onToggle={vi.fn()} />); expect(screen.getAllByText(/Matcha Latte/).length).toBeGreaterThan(0); expect(screen.getByText(/Nhỏ.*Vừa/)).toBeTruthy(); expect(screen.getByText(/Đã cấp 4/)).toBeTruthy(); expect(screen.getByText(/Đã dùng 2/)).toBeTruthy(); expect(screen.getByText(/Còn lại Không giới hạn/)).toBeTruthy(); });
  it("detail hiển thị tên cấu hình và cách nhận đầy đủ", () => { const product = { ...pkg, voucher_type: "PRODUCT" as const, acquisition_mode: "POINTS_EXCHANGE" as const, points_cost: 8, size: "MEDIUM" as const, matcha_powder_id: "powder", milk_type_id: "milk", included_addon_option_ids: ["addon"], covered_price_vnd: 65_000 }; render(<AdminVoucherPackageDetail pkg={product} open saving={false} onClose={vi.fn()} onSave={vi.fn()} onToggle={vi.fn()} powderLabels={new Map([["powder", "Hana"]])} baseLiquidLabels={new Map([["milk", "Sữa yến mạch"]])} addonLabels={new Map([["addon", "Kem cheese"]])} />); expect(screen.getByText(/Đổi 8 điểm/)).toBeTruthy(); expect(screen.getByText(/Hana/)).toBeTruthy(); expect(screen.getByText(/Sữa yến mạch/)).toBeTruthy(); expect(screen.getByText(/Kem cheese/)).toBeTruthy(); expect(screen.getByText(/65.000đ/)).toBeTruthy(); });
  it("card unlimited chưa cấp tránh 0 trên 0 và nêu chưa sử dụng", () => { render(<AdminVoucherPackageCard pkg={{ ...pkg, stats: { ...pkg.stats!, issued_count: 0, redeemed_count: 0 } }} onOpen={vi.fn()} />); expect(screen.getByText("Đã cấp 0 · Không giới hạn · Chưa có lượt sử dụng")).toBeTruthy(); });
  it("tìm mới dùng query mới và đổi trạng thái không trộn phân trang", async () => { mockSearchOwners.mockResolvedValueOnce({ users: [], next_cursor: "next" }).mockResolvedValue({ users: [], next_cursor: null }); render(<AdminVoucherPackageDetail pkg={pkg} open saving={false} onClose={vi.fn()} onSave={vi.fn()} onToggle={vi.fn()} />); const input = screen.getByPlaceholderText("Tên, Instagram, số điện thoại"); fireEvent.change(input, { target: { value: "an" } }); fireEvent.submit(input.closest("form")!); await screen.findByText("Tải thêm"); fireEvent.change(input, { target: { value: "binh" } }); fireEvent.click(screen.getByText("Tải thêm")); await waitFor(() => expect(mockSearchOwners).toHaveBeenLastCalledWith("pkg", { q: "an", status: "ALL", cursor: "next" })); fireEvent.change(screen.getByLabelText("Trạng thái voucher"), { target: { value: "ACTIVE" } }); expect(screen.queryByText("Tải thêm")).toBeNull(); fireEvent.submit(input.closest("form")!); await waitFor(() => expect(mockSearchOwners).toHaveBeenLastCalledWith("pkg", expect.objectContaining({ q: "binh", status: "ACTIVE" }))); });
  it("đóng khi draft bẩn yêu cầu xác nhận bỏ thay đổi", () => { render(<AdminVoucherPackageDetail pkg={pkg} open saving={false} onClose={vi.fn()} onSave={vi.fn()} onToggle={vi.fn()} />); fireEvent.click(screen.getByLabelText("Sửa tên")); fireEvent.change(screen.getByLabelText("Tên package"), { target: { value: "Tên nháp" } }); fireEvent.click(screen.getByText("Đóng overlay")); expect(screen.getByText("Bỏ thay đổi chưa lưu?")).toBeTruthy(); });
  it("lưu lỗi giữ nguyên draft và hiển thị lỗi tại field", async () => { const onSave = vi.fn().mockRejectedValue(new Error("Tên đã tồn tại")); render(<AdminVoucherPackageDetail pkg={pkg} open saving={false} onClose={vi.fn()} onSave={onSave} onToggle={vi.fn()} />); fireEvent.click(screen.getByLabelText("Sửa tên")); fireEvent.change(screen.getByLabelText("Tên package"), { target: { value: "Tên nháp" } }); fireEvent.click(screen.getByLabelText("Lưu")); expect(await screen.findByText("Tên đã tồn tại")).toBeTruthy(); expect((screen.getByLabelText("Tên package") as HTMLInputElement).value).toBe("Tên nháp"); });
  it("package đã kết thúc không có thao tác phát hành lại", () => { render(<AdminVoucherPackageDetail pkg={{ ...pkg, is_active: false, ends_at: "2020-01-01T00:00:00Z" }} open saving={false} onClose={vi.fn()} onSave={vi.fn()} onToggle={vi.fn()} />); expect(screen.queryByText("Tiếp tục phát hành")).toBeNull(); });
  it("khóa nút tìm và bỏ qua response cũ khi request chồng nhau", async () => { let resolveOld: (value: { users: Array<{ qr_token: string; name: string; insta_name: null; phone_number: string; vouchers: [] }>; next_cursor: null }) => void = () => undefined; const oldPromise = new Promise<{ users: Array<{ qr_token: string; name: string; insta_name: null; phone_number: string; vouchers: [] }>; next_cursor: null }>((resolve) => { resolveOld = resolve; }); mockSearchOwners.mockReturnValueOnce(oldPromise).mockResolvedValueOnce({ users: [{ qr_token: "new", name: "Kết quả mới", insta_name: null, phone_number: "+8490", vouchers: [] }], next_cursor: null }); render(<AdminVoucherPackageDetail pkg={pkg} open saving={false} onClose={vi.fn()} onSave={vi.fn()} onToggle={vi.fn()} />); const input = screen.getByPlaceholderText("Tên, Instagram, số điện thoại"); fireEvent.change(input, { target: { value: "cu" } }); fireEvent.submit(input.closest("form")!); expect((screen.getByRole("button", { name: "Đang tìm" }) as HTMLButtonElement).disabled).toBe(true); fireEvent.change(input, { target: { value: "moi" } }); fireEvent.submit(input.closest("form")!); await screen.findByText("Kết quả mới"); resolveOld({ users: [{ qr_token: "old", name: "Kết quả cũ", insta_name: null, phone_number: "+8491", vouchers: [] }], next_cursor: null }); await waitFor(() => expect(screen.queryByText("Kết quả cũ")).toBeNull()); });
  it("không nhận response tìm kiếm của package cũ sau khi chuyển package", async () => { let resolveA: (value: { users: Array<{ qr_token: string; name: string; insta_name: null; phone_number: string; vouchers: [] }>; next_cursor: null }) => void = () => undefined; mockSearchOwners.mockReturnValueOnce(new Promise((resolve) => { resolveA = resolve; })); const view = render(<AdminVoucherPackageDetail pkg={{ ...pkg, id: "package-a" }} open saving={false} onClose={vi.fn()} onSave={vi.fn()} onToggle={vi.fn()} />); const input = screen.getByPlaceholderText("Tên, Instagram, số điện thoại"); fireEvent.change(input, { target: { value: "anna" } }); fireEvent.submit(input.closest("form")!); view.rerender(<AdminVoucherPackageDetail pkg={{ ...pkg, id: "package-b", name: "Package B" }} open saving={false} onClose={vi.fn()} onSave={vi.fn()} onToggle={vi.fn()} />); await act(async () => { resolveA({ users: [{ qr_token: "owner-a", name: "Chủ package A", insta_name: null, phone_number: "+8490", vouchers: [] }], next_cursor: null }); await Promise.resolve(); }); expect(screen.queryByText("Chủ package A")).toBeNull(); expect(screen.getByText("Package B")).toBeTruthy(); });
  it("scope extras và relation thiếu không làm lộ UUID", () => { const rawMenuId = "550e8400-e29b-41d4-a716-446655440099"; const bundle = { ...pkg, voucher_type: "BUNDLE" as const, menu_item_id: null, bundleRule: { buy_quantity: 1, reward_quantity: 1, reward_kind: "PRODUCT" as const, reward_mode: "ALLOWED_SCOPE" as const, benefit_scaling: "PER_BUNDLE" as const, max_applications_per_order: 1, qualifier_products: [{ menu_item_id: rawMenuId, allowed_sizes: [], menu_item: undefined }], reward_products: [], reward_addon_option_ids: [] } }; const view = render(<AdminVoucherPackageDetail pkg={bundle} open saving={false} onClose={vi.fn()} onSave={vi.fn()} onToggle={vi.fn()} menuItemLookup={new Map([[rawMenuId, { label: "Bánh cookie", category: "extras" }]])} />); const scope = screen.getByText(/Món mua: Bánh cookie/); expect(scope.textContent).not.toMatch(/Size|bột|Base Liquid/); expect(document.body.textContent).not.toContain(rawMenuId); view.rerender(<AdminVoucherPackageDetail pkg={{ ...pkg, voucher_type: "ITEM", menu_item_id: rawMenuId, menuItem: null }} open saving={false} onClose={vi.fn()} onSave={vi.fn()} onToggle={vi.fn()} />); expect(document.body.textContent).not.toContain(rawMenuId); expect(screen.getByText(/Món tặng: Không còn trong danh mục/)).toBeTruthy(); });
});
