"use client";

import { useEffect, useRef, useState } from "react";
import { Check, Loader2, Pencil, Search, X } from "lucide-react";

import { ConfirmModal } from "@/src/components/ui/ConfirmModal";
import { ResponsiveOverlay } from "@/src/components/ui/ResponsiveOverlay";
import type { UpdateVoucherPackageInput, VoucherBundleProductScope, VoucherOwnerPage, VoucherOwnerStatus, VoucherPackage } from "@/src/services/adminVoucherService";
import { searchVoucherPackageOwners } from "@/src/services/adminVoucherService";
import { getVoucherPackageStatus, summarizeVoucherBenefit } from "@/src/lib/utils/adminVoucherPresentation";
import { formatInclusiveEndDate } from "@/src/lib/utils/adminVoucherForm";

type EditableField = "name" | "description";
const OWNER_STATUSES: VoucherOwnerStatus[] = ["ALL", "ACTIVE", "RESERVED", "REDEEMED", "EXPIRED", "REFUNDED"];
const STATUS_LABEL: Record<VoucherOwnerStatus, string> = { ALL: "Tất cả", ACTIVE: "Đang dùng", RESERVED: "Đã giữ", REDEEMED: "Đã dùng", EXPIRED: "Hết hạn", REFUNDED: "Đã hoàn" };
const REWARD_MODE = { SAME_CONFIG: "Cùng cấu hình món mua", FIXED_CONFIG: "Cấu hình cố định", ALLOWED_SCOPE: "Chọn trong phạm vi" } as const;
const BENEFIT_SCALING = { PER_BUNDLE: "Theo mỗi combo", ONCE_PER_ORDER: "Một lần mỗi đơn", PER_QUALIFYING_ITEM: "Theo mỗi món đủ điều kiện" } as const;
const SIZE_LABEL = { SMALL: "Nhỏ", MEDIUM: "Vừa", LARGE: "Lớn" } as const;
type MenuItemLookup = ReadonlyMap<string, { label: string; category: "latte" | "fusion" | "extras" }>;
type LookupProps = { powderLabels?: ReadonlyMap<string, string>; baseLiquidLabels?: ReadonlyMap<string, string>; addonLabels?: ReadonlyMap<string, string>; menuItemLookup?: MenuItemLookup };

/** Renders package detail, inline editing, issuance controls, and owner search. */
export function AdminVoucherPackageDetail({ pkg, open, saving, onClose, onSave, onToggle, powderLabels = new Map(), baseLiquidLabels = new Map(), addonLabels = new Map(), menuItemLookup = new Map() }: { pkg: VoucherPackage | null; open: boolean; saving: boolean; onClose: () => void; onSave: (input: UpdateVoucherPackageInput) => Promise<void>; onToggle: () => Promise<void> } & LookupProps) {
  const [editing, setEditing] = useState<EditableField | null>(null);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [error, setError] = useState("");
  const [discardOpen, setDiscardOpen] = useState(false); const [toggleOpen, setToggleOpen] = useState(false); const [toggling, setToggling] = useState(false);
  const sessionKey = useRef<string | null>(null);
  const requestGeneration = useRef(0);
  const packageRef = useRef(pkg); packageRef.current = pkg;
  const [query, setQuery] = useState(""); const [submittedQuery, setSubmittedQuery] = useState(""); const [ownerStatus, setOwnerStatus] = useState<VoucherOwnerStatus>("ALL"); const [submittedStatus, setSubmittedStatus] = useState<VoucherOwnerStatus>("ALL");
  const [owners, setOwners] = useState<VoucherOwnerPage>({ users: [], next_cursor: null }); const [searching, setSearching] = useState(false); const [searchError, setSearchError] = useState("");
  useEffect(() => { const current = packageRef.current; const key = open && current ? current.id : null; if (sessionKey.current === key) return; sessionKey.current = key; requestGeneration.current += 1; setSearching(false); setSearchError(""); setOwners({ users: [], next_cursor: null }); setSubmittedQuery(""); setQuery(""); if (current && open) { setName(current.name); setDescription(current.description ?? ""); setEditing(null); setError(""); setSubmittedStatus("ALL"); setOwnerStatus("ALL"); } }, [open, pkg?.id]);
  if (!pkg) return null;
  const dirty = name !== pkg.name || description !== (pkg.description ?? "");
  const operationalStatus = getVoucherPackageStatus(pkg);
  const stats = pkg.stats ?? { issued_count: 0, active_count: 0, reserved_count: 0, redeemed_count: 0, expired_count: 0, refunded_count: 0, remaining_quantity: pkg.quantity };
  const canToggle = operationalStatus === "ACTIVE" || operationalStatus === "PAUSED";
  const requestClose = () => dirty ? setDiscardOpen(true) : onClose();
  const saveField = async (field: EditableField) => { setError(""); try { await onSave(field === "name" ? { name: name.trim() } : { description: description.trim() || null }); setEditing(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Không thể lưu thay đổi"); } };
  const runSearch = async (cursor?: string) => { const q = cursor ? submittedQuery : query.trim(); const status = cursor ? submittedStatus : ownerStatus; if (q.length < 2) { setSearchError("Nhập ít nhất 2 ký tự"); return; } const generation = ++requestGeneration.current; setSearching(true); setSearchError(""); try { const page = await searchVoucherPackageOwners(pkg.id, { q, status, ...(cursor ? { cursor } : {}) }); if (generation !== requestGeneration.current) return; if (!cursor) { setSubmittedQuery(q); setSubmittedStatus(status); } setOwners((current) => ({ users: cursor ? [...current.users, ...page.users] : page.users, next_cursor: page.next_cursor })); } catch { if (generation === requestGeneration.current) setSearchError("Không thể tìm chủ sở hữu"); } finally { if (generation === requestGeneration.current) setSearching(false); } };
  const editor = (field: EditableField, value: string, setValue: (value: string) => void) => <div className="space-y-2"><div className="flex items-start gap-2">{editing === field ? <>{field === "description" ? <textarea aria-label="Mô tả" value={value} onChange={(event) => setValue(event.target.value)} className="min-h-24 flex-1 rounded-xl border p-3" /> : <input aria-label="Tên package" value={value} onChange={(event) => setValue(event.target.value)} className="h-11 flex-1 rounded-xl border px-3" />}<button type="button" className="grid h-10 w-10 place-items-center" onClick={() => saveField(field)} aria-label="Lưu"><Check /></button><button type="button" className="grid h-10 w-10 place-items-center" onClick={() => { setValue(field === "name" ? pkg.name : pkg.description ?? ""); setEditing(null); setError(""); }} aria-label="Huỷ sửa"><X /></button></> : <><p className="min-w-0 flex-1 whitespace-pre-wrap">{value || "Chưa có mô tả"}</p><button type="button" className="grid h-10 w-10 place-items-center" onClick={() => setEditing(field)} aria-label={`Sửa ${field === "name" ? "tên" : "mô tả"}`}><Pencil className="h-4 w-4" /></button></>}</div>{editing === field && error ? <p className="text-sm text-destructive">{error}</p> : null}</div>;
  const typeDetails = () => {
    if (pkg.voucher_type === "PRODUCT") return <div><p>Sản phẩm: {pkg.menuItem?.name ?? "Không xác định"} · Size {pkg.size ? SIZE_LABEL[pkg.size] : "không giới hạn"}</p><p>Bột: {pkg.matcha_powder_id ? powderLabels.get(pkg.matcha_powder_id) ?? "Không còn trong danh mục" : "Mặc định"} · Base Liquid: {pkg.milk_type_id ? baseLiquidLabels.get(pkg.milk_type_id) ?? "Không còn trong danh mục" : "Mặc định"}</p><p>Addon kèm: {pkg.included_addon_option_ids.map((id) => addonLabels.get(id) ?? "Không còn trong danh mục").join(", ") || "Không có"} · Giá trị bao phủ {(pkg.covered_price_vnd ?? 0).toLocaleString("vi-VN")}đ</p></div>;
    if (pkg.voucher_type === "PRODUCT_DISCOUNT") return <div><p>Món áp dụng: {(pkg.eligible_menu_items ?? []).map((item) => item.name).join(", ") || pkg.menuItem?.name}</p><p>Size: {(pkg.eligible_sizes ?? []).map((size) => SIZE_LABEL[size]).join(", ")} · Chế độ {pkg.product_discount_mode === "PAY_AS_SIZE" ? `Trả theo size ${pkg.reference_size ? SIZE_LABEL[pkg.reference_size] : "tham chiếu"}` : `Giảm cố định ${(pkg.discount_value ?? 0).toLocaleString("vi-VN")}đ`}</p></div>;
    if (pkg.voucher_type === "BUNDLE" && pkg.bundleRule) { const scopeLabel = (scope: VoucherBundleProductScope) => { const lookup = menuItemLookup.get(scope.menu_item_id); const name = scope.menu_item?.name ?? lookup?.label ?? "Không còn trong danh mục"; if ((scope.menu_item?.category ?? lookup?.category) === "extras") return name; return `${name} (${scope.allowed_sizes.map((size) => SIZE_LABEL[size]).join("/")}; bột ${scope.default_powder_id ? powderLabels.get(scope.default_powder_id) ?? "không còn" : "mặc định"}; Base Liquid ${scope.default_base_liquid_id ? baseLiquidLabels.get(scope.default_base_liquid_id) ?? "không còn" : "mặc định"})`; }; return <div><p>Cách nhận thưởng: {REWARD_MODE[pkg.bundleRule.reward_mode]} · {BENEFIT_SCALING[pkg.bundleRule.benefit_scaling]}</p><p>Món mua: {pkg.bundleRule.qualifier_products.map(scopeLabel).join(", ") || "Không có"}</p><p>Phần thưởng: {pkg.bundleRule.reward_kind === "PRODUCT" ? pkg.bundleRule.reward_products.map(scopeLabel).join(", ") : pkg.bundleRule.reward_addon_option_ids.map((id) => addonLabels.get(id) ?? "Addon không còn trong danh mục").join(", ")} · Tối đa {pkg.bundleRule.max_applications_per_order} lần/đơn{pkg.bundleRule.max_reward_units_per_order ? ` · ${pkg.bundleRule.max_reward_units_per_order} phần thưởng/đơn` : ""}</p></div>; }
    if (pkg.voucher_type === "ADDON") return <p>Addon áp dụng: {pkg.addonOption?.label ?? (pkg.addon_option_id ? addonLabels.get(pkg.addon_option_id) : null) ?? "Không còn trong danh mục"}</p>;
    if (pkg.voucher_type === "ITEM") return <p>Món tặng: {pkg.menuItem?.name ?? (pkg.menu_item_id ? menuItemLookup.get(pkg.menu_item_id)?.label : null) ?? "Không còn trong danh mục"}</p>;
    if (pkg.voucher_type === "DISCOUNT") return <p>{pkg.discount_type === "PERCENT" ? `Giảm ${pkg.discount_value}%` : `Giảm ${(pkg.discount_value ?? 0).toLocaleString("vi-VN")}đ`}</p>;
    return <p>Hỗ trợ tối đa {(pkg.covered_delivery_fee_vnd ?? 0).toLocaleString("vi-VN")}đ phí giao</p>;
  };
  return <><ResponsiveOverlay open={open} onOpenChange={(next) => { if (!next) requestClose(); }} title="Chi tiết package" description="Theo dõi phát hành và người sở hữu" size="lg" dismissPolicy={saving ? "locked-while-busy" : "default"} busy={saving} footer={canToggle ? <button type="button" disabled={saving || toggling} onClick={() => setToggleOpen(true)} className="flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-primary font-semibold text-primary-foreground disabled:opacity-60">{(saving || toggling) ? <Loader2 className="h-4 w-4 animate-spin" /> : pkg.is_active ? "Tạm dừng phát hành" : "Tiếp tục phát hành"}</button> : undefined}>
    <div className="space-y-6">
      <section className="space-y-3">{editor("name", name, setName)}{editor("description", description, setDescription)}<div className="space-y-2 rounded-xl bg-muted p-3 text-sm"><p>Cách nhận: {pkg.acquisition_mode === "POINTS_EXCHANGE" ? `Đổi ${pkg.points_cost} điểm` : pkg.acquisition_mode === "AUTO_GRANT" ? "Tự động cấp" : "Nhận miễn phí"}</p><p>{summarizeVoucherBenefit(pkg)}</p>{typeDetails()}</div></section>
      <section className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl border p-3">Đã cấp {stats.issued_count}</div><div className="rounded-xl border p-3">Đã dùng {stats.redeemed_count}</div><div className="rounded-xl border p-3">Còn lại {stats.remaining_quantity === null ? "Không giới hạn" : stats.remaining_quantity}</div><div className="rounded-xl border p-3">Đang hiệu lực {stats.active_count}</div><div className="rounded-xl border p-3">Đã giữ {stats.reserved_count}</div><div className="rounded-xl border p-3">Hết hạn {stats.expired_count}</div><div className="rounded-xl border p-3">Đã hoàn {stats.refunded_count}</div><div className="rounded-xl border p-3">Mỗi khách tối đa {pkg.max_per_user}</div></section>
      <section className="space-y-2 text-sm"><h3 className="font-bold">Điều kiện & thời hạn</h3><p>{pkg.min_order_vnd ? `Đơn tối thiểu ${pkg.min_order_vnd.toLocaleString("vi-VN")}đ` : "Không yêu cầu giá trị đơn tối thiểu"}</p><p>{pkg.ends_at ? `Hạn phát hành: ${formatInclusiveEndDate(pkg.ends_at)}` : "Không giới hạn hạn phát hành"} · {pkg.expires_after_days ? `Có hiệu lực ${pkg.expires_after_days} ngày sau cấp` : "Không giới hạn hiệu lực"}</p></section>
      <section className="space-y-3"><h3 className="font-bold">Tìm chủ sở hữu</h3><form onSubmit={(event) => { event.preventDefault(); void runSearch(); }} className="flex gap-2"><label className="flex h-11 flex-1 items-center gap-2 rounded-xl border px-3"><Search className="h-4 w-4" /><span className="sr-only">Tên, Instagram hoặc số điện thoại</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tên, Instagram, số điện thoại" className="min-w-0 flex-1 bg-transparent outline-none" /></label><button disabled={searching} aria-label={searching ? "Đang tìm" : "Tìm"} className="grid h-11 min-w-16 place-items-center rounded-xl bg-primary px-4 text-primary-foreground disabled:opacity-60">{searching ? <Loader2 className="h-4 w-4 animate-spin" /> : "Tìm"}</button></form>
        <select aria-label="Trạng thái voucher" value={ownerStatus} onChange={(event) => { requestGeneration.current += 1; setSearching(false); setOwnerStatus(event.target.value as VoucherOwnerStatus); setOwners({ users: [], next_cursor: null }); setSubmittedQuery(""); }} className="h-11 w-full rounded-xl border bg-background px-3">{OWNER_STATUSES.map((status) => <option key={status} value={status}>{STATUS_LABEL[status]}</option>)}</select>
        {searchError ? <p className="text-sm text-destructive">{searchError}</p> : null}{owners.users.map((owner) => <article key={owner.qr_token} className="rounded-xl border p-3"><p className="font-semibold">{owner.name}</p><p className="text-xs text-muted-foreground">{owner.insta_name ? `@${owner.insta_name} · ` : ""}{owner.phone_number}</p><div className="mt-2 space-y-1">{owner.vouchers.map((voucher) => <p key={voucher.qr_token} className="text-xs">{voucher.effective_status} · {new Date(voucher.created_at).toLocaleDateString("vi-VN")}</p>)}</div></article>)}
        {owners.next_cursor ? <button type="button" disabled={searching} onClick={() => void runSearch(owners.next_cursor ?? undefined)} className="h-11 w-full rounded-xl border">{searching ? <Loader2 className="mx-auto animate-spin" /> : "Tải thêm"}</button> : null}
      </section>
    </div>
  </ResponsiveOverlay><ConfirmModal isOpen={discardOpen} title="Bỏ thay đổi chưa lưu?" message="Tên hoặc mô tả đang có thay đổi chưa lưu." isDestructive confirmLabel="Bỏ thay đổi" onCancel={() => setDiscardOpen(false)} onConfirm={() => { setDiscardOpen(false); onClose(); }} /><ConfirmModal isOpen={toggleOpen} title={pkg.is_active ? "Tạm dừng phát hành?" : "Tiếp tục phát hành?"} message={pkg.is_active ? "Voucher đã cấp vẫn dùng được; chỉ dừng cấp mới." : "Khách phù hợp có thể nhận voucher trở lại."} isDestructive={pkg.is_active} isLoading={toggling} onCancel={() => { if (!toggling) setToggleOpen(false); }} onConfirm={() => { setToggling(true); void onToggle().finally(() => { setToggling(false); setToggleOpen(false); }); }} /></>;
}
