/**
 * Edge-compatible session operations using Supabase PostgREST API.
 *
 * This module replaces the self-fetch anti-pattern in middleware.ts.
 * Prisma does not work in Edge Runtime — PostgREST is zero-dependency
 * and works with the existing NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY.
 */

/** Session row joined with user data — returned by findSessionWithUser. */
export interface SessionWithUser {
  id: string;
  user_id: string;
  refresh_token: string;
  expires_at: string;
  user: {
    id: string;
    role: string;
    phone_number: string;
  };
}

/** New session data returned by createSession. */
export interface NewSession {
  refresh_token: string;
  expires_at: string;
}

/**
 * Returns base URL and auth headers for Supabase PostgREST.
 * Throws if env vars are missing.
 */
function getSupabaseConfig(): { baseUrl: string; headers: Record<string, string> } {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceKey) {
    throw new Error("Supabase env vars missing: NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required");
  }

  return {
    baseUrl: `${supabaseUrl}/rest/v1`,
    headers: {
      "apikey": serviceKey,
      "Authorization": `Bearer ${serviceKey}`,
      "Content-Type": "application/json",
    },
  };
}

/**
 * Finds a session by refresh_token and joins the user row.
 * Returns null if not found, expired, or on network error.
 */
export async function findSessionWithUser(refreshToken: string): Promise<SessionWithUser | null> {
  try {
    const { baseUrl, headers } = getSupabaseConfig();
    const url = new URL(`${baseUrl}/sessions`);
    url.searchParams.set("refresh_token", `eq.${refreshToken}`);
    url.searchParams.set("select", "id,user_id,refresh_token,expires_at,user:users(id,role,phone_number)");
    url.searchParams.set("limit", "1");

    const res = await fetch(url.toString(), { headers });

    if (!res.ok) return null;

    const rows = (await res.json()) as SessionWithUser[];
    return rows.length > 0 ? rows[0] : null;
  } catch {
    return null;
  }
}

/**
 * Deletes a session by id. Fire-and-forget — never throws.
 */
export async function deleteSession(sessionId: string): Promise<void> {
  try {
    const { baseUrl, headers } = getSupabaseConfig();
    const url = new URL(`${baseUrl}/sessions`);
    url.searchParams.set("id", `eq.${sessionId}`);

    await fetch(url.toString(), { method: "DELETE", headers });
  } catch {
    // Best-effort — failure here should not block the auth flow
  }
}

/**
 * Creates a new session for a user.
 * Returns the new refresh_token (generated by Postgres) and expires_at.
 * Throws on failure — caller must handle.
 */
export async function createSession(userId: string): Promise<NewSession> {
  const { baseUrl, headers } = getSupabaseConfig();
  const url = new URL(`${baseUrl}/sessions`);

  const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); // 7 days

  const res = await fetch(url.toString(), {
    method: "POST",
    headers: {
      ...headers,
      "Prefer": "return=representation",
    },
    body: JSON.stringify({
      user_id: userId,
      expires_at: expiresAt.toISOString(),
    }),
  });

  if (!res.ok) {
    throw new Error(`Failed to create session: HTTP ${res.status}`);
  }

  const rows = (await res.json()) as NewSession[];
  if (!rows.length) {
    throw new Error("Failed to create session: empty response from PostgREST");
  }

  return rows[0];
}
