/**
 * Edge-compatible session operations using Supabase PostgREST API.
 *
 * This module replaces the self-fetch anti-pattern in middleware.ts.
 * Prisma does not work in Edge Runtime — PostgREST is zero-dependency
 * and works with NEXT_PUBLIC_SUPABASE_URL + a server-only Supabase secret key.
 *
 * Refresh-token validation is always authoritative through PostgREST. Redis
 * cache keys from older releases are only evicted and are never trusted.
 */

import { cacheDelete } from './redis';

/** Session row joined with user data — returned by findSessionWithUser. */
export interface SessionWithUser {
  id: string;
  user_id: string;
  refresh_token: string;
  expires_at: string;
  user: {
    id: string;
    role: string;
    phone_number: string;
  };
}

/** New session data returned by createSession. */
export interface NewSession {
  refresh_token: string;
  expires_at: string;
}

/** Outcome of an authoritative refresh-session rotation claim. */
export type RotationClaim = "acquired" | "not_acquired" | "error";

/**
 * Returns base URL and auth headers for Supabase PostgREST.
 * Throws if env vars are missing.
 */
function getSupabaseConfig(): { baseUrl: string; headers: Record<string, string> } {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  // One-release compatibility bridge; remove the legacy fallback after rollout.
  const secretKey = process.env.SUPABASE_SECRET_KEY;
  const legacyServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const serviceKey = secretKey || legacyServiceRoleKey;

  if (!supabaseUrl || !serviceKey) {
    throw new Error(
      "Supabase env vars missing: NEXT_PUBLIC_SUPABASE_URL and a server secret key are required",
    );
  }

  const headers: Record<string, string> = {
    "apikey": serviceKey,
    "Content-Type": "application/json",
  };
  if (!secretKey && legacyServiceRoleKey) {
    headers["Authorization"] = `Bearer ${legacyServiceRoleKey}`;
  }

  return {
    baseUrl: `${supabaseUrl}/rest/v1`,
    headers,
  };
}

/**
 * Finds a session by refresh_token and joins the user row.
 * Always checks PostgREST so a revoked DB row cannot survive through Redis.
 * Returns null if not found, expired, or on network error.
 */
export async function findSessionWithUser(refreshToken: string): Promise<SessionWithUser | null> {
  try {
    const { baseUrl, headers } = getSupabaseConfig();
    const url = new URL(`${baseUrl}/sessions`);
    url.searchParams.set("refresh_token", `eq.${refreshToken}`);
    url.searchParams.set("select", "id,user_id,refresh_token,expires_at,user:users(id,role,phone_number)");
    url.searchParams.set("limit", "1");

    const res = await fetch(url.toString(), { headers });

    if (!res.ok) return null;

    const rows = (await res.json()) as SessionWithUser[];
    return rows.length > 0 ? rows[0] : null;
  } catch {
    return null;
  }
}

/**
 * Deletes a session by id. Also removes from Redis cache.
 * Best-effort — never throws.
 */
export async function deleteSession(sessionId: string, refreshToken?: string): Promise<void> {
  try {
    const { baseUrl, headers } = getSupabaseConfig();
    const url = new URL(`${baseUrl}/sessions`);
    url.searchParams.set("id", `eq.${sessionId}`);

    await fetch(url.toString(), { method: "DELETE", headers });

    // Also evict from Redis cache if caller passes the refreshToken (awaited — Edge Runtime)
    if (refreshToken) {
      await cacheDelete(`session:${refreshToken}`);
    }
  } catch {
    // Best-effort — failure here should not block the auth flow
  }
}

/**
 * Evicts the session cache for a given refresh token.
 * Call this immediately after token rotation to prevent replay of the old token.
 * Best-effort — never throws.
 */
export async function evictSessionCache(refreshToken: string): Promise<void> {
  try {
    await cacheDelete(`session:${refreshToken}`);
  } catch {
    // Best-effort
  }
}

/**
 * Truncates a session's lifetime to 30 seconds (Grace Period for Token Rotation).
 * This prevents concurrent middleware requests from seeing a missing session.
 */
export async function updateSessionGracePeriod(sessionId: string): Promise<boolean> {
  try {
    const { baseUrl, headers } = getSupabaseConfig();
    const url = new URL(`${baseUrl}/sessions`);
    url.searchParams.set("id", `eq.${sessionId}`);

    const res = await fetch(url.toString(), {
      method: "PATCH",
      headers: { ...headers, "Prefer": "return=representation" },
      body: JSON.stringify({ expires_at: new Date(Date.now() + 30 * 1000).toISOString() }),
    });
    if (!res.ok) return false;
    const rows = (await res.json()) as unknown[];
    return Array.isArray(rows) && rows.length > 0;
  } catch {
    return false;
  }
}

/**
 * Creates a new session for a user.
 * Returns the new refresh_token (generated by Postgres) and expires_at.
 * Throws on failure — caller must handle.
 */
export async function createSession(userId: string): Promise<NewSession> {
  const { baseUrl, headers } = getSupabaseConfig();
  const url = new URL(`${baseUrl}/sessions`);

  const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); // 7 days

  const res = await fetch(url.toString(), {
    method: "POST",
    headers: {
      ...headers,
      "Prefer": "return=representation",
    },
    body: JSON.stringify({
      user_id: userId,
      expires_at: expiresAt.toISOString(),
    }),
  });

  if (!res.ok) {
    throw new Error(`Failed to create session: HTTP ${res.status}`);
  }

  const rows = (await res.json()) as NewSession[];
  if (!rows.length) {
    throw new Error("Failed to create session: empty response from PostgREST");
  }

  return rows[0];
}

/**
 * Atomically acquires a rotation lock on a session row via PostgREST.
 *
 * Uses an optimistic-locking PATCH:
 *   UPDATE sessions SET rotating_at = NOW()
 *   WHERE id = $id AND (rotating_at IS NULL OR rotating_at < NOW() - 30s)
 *
 * Returns true  → lock acquired — caller should proceed with rotation.
 * Returns false → another request holds the lock — caller should skip rotation
 *                 (the winning request will set the new cookies on its response).
 *
 * Stale locks older than 30 seconds are automatically overridden to handle
 * the edge case where a rotation process crashed mid-flight.
 */
export async function markSessionRotating(sessionId: string): Promise<RotationClaim> {
  try {
    const { baseUrl, headers } = getSupabaseConfig();
    const staleThreshold = new Date(Date.now() - 30_000).toISOString();

    // PostgREST filter: id=eq.{id} AND (rotating_at IS NULL OR rotating_at < staleThreshold)
    const url = new URL(`${baseUrl}/sessions`);
    url.searchParams.set("id", `eq.${sessionId}`);
    url.searchParams.set("or", `(rotating_at.is.null,rotating_at.lt.${staleThreshold})`);

    const res = await fetch(url.toString(), {
      method: "PATCH",
      headers: {
        ...headers,
        "Prefer": "return=representation",
      },
      body: JSON.stringify({ rotating_at: new Date().toISOString() }),
    });

    if (!res.ok) return "error";
    const rows = (await res.json()) as unknown[];
    return Array.isArray(rows) && rows.length > 0 ? "acquired" : "not_acquired";
  } catch {
    return "error";
  }
}

